#!/bin/bash

###################
# Clone bare repo #
###################
if [ -z "$2" ]; then
  git clone --bare $1 $HOME/.cfg
else
  git clone --single-branch --bare --branch $2 $1 $HOME/.cfg
fi;

###############################
# Set repo path and work tree #
###############################
function config {
  /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}

############################
# Attempt to checkout repo #
############################
config checkout

####################
# Handle conflicts #
####################
if [ $? = 0 ]; then
  echo "Checked out config.";
else
  echo "Backing up pre-existing dot files.";
  mkdir -p .config-backup
  config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;

############################
# Attempt to checkout repo #
############################
config checkout

########################
# Update repo settings #
########################
config config status.showUntrackedFiles no

#######################
# Source bash profile #
#######################
source ~/.bash_profile
